version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_engine
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  devblog:
    build: .
    ports:
      - "8080:8080"
    container_name: devblog
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/blog_engine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  db-data: