server:
  port: ${PORT:8080}
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/blog_engine?&useSSL=false&serverTimezone=UTC}
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/databaseChangeLog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.yandex.ru
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  sql:
    init:
      mode: always
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 664-44-55
  email: ruslan@mail.ru
  copyright: Ruslan Saberov
  copyrightFrom: 2021

upload:
  path: src/main/resources/upload
